### ISSUE TITLE
angularApp.component is not a function

### ISSUE THREAD

**Issue by shyam041** [xjpro/react-in-angularjs#15]
I am trying to migrate application which is running in angularJs 1.3.3 to react.
While doing this I am getting below error:

Uncaught TypeError: angularApp.component is not a function
    at angularize

please let me know the prerequisites to use this package for migration

**Comment by DDani** [comment]
Hi! the .component function was added above 1.5.x angular versions:

https://code.angularjs.org/1.5.10/docs/guide/component

I guess, you should upgrade; in my case I'm using react-in-angularjs with angular 1.8.2 and is working fine.

**Comment by xjpro** [comment]
@shyam041 Yes, this library currently uses app.component as @DDani pointed out. Any chance you can upgrade? I don't think we'll be writing the library to use older versions of directives.
