### ISSUE TITLE
could you please provide a bundle file with umd module type?

### ISSUE THREAD

**Issue by jueinin** [xjpro/react-in-angularjs#6]
our obsolete project is using requirejs to manage module. the commonjs module is not compatiable with requirejs.

I am trying to rewrite it to requirejs

**Comment by jueinin** [comment]
emmm... it's a project with angularjs v1.3.x version. without the module.component API. too awkward!

**Comment by xjpro** [comment]
There’s a directive version of angularize, would that work? https://github.com/xjpro/react-in-angularjs#directives

**Comment by jueinin** [comment]
I have not tried the directive version yet.  because of the lack of `module.component` api and life cycle hooks in angularjs v1.3. I have tried the [polyfill](https://github.com/toddmotto/angular-component) . It works, but the change of $scope won't sync to react component. i guess the reason may be  that the polyfill do not implement `$doCheck` api. Do you have any ideas to use React in augularjs v1.3.x project?

**Comment by xjpro** [comment]
Here's the function in question, perhaps you could take only this function for use in your older project?

https://github.com/xjpro/react-in-angularjs/blob/e5c2cc10f74ba05a07057e389aef8e996f92a968/src/index.js#L46

I made this project public domain so feel free to just snip what you need.

**Comment by jueinin** [comment]
it works by using angularizeDirective function, thanks! what do you think frontend microservice? it  seems a better solution. I really do not want to write angularjs code....

**Comment by xjpro** [comment]
I'd recommend React, Vue, or Angular (the new one, not AngularJS). React is my choice but they all have their merits. `react-in-angularjs` is not meant to be used forever, it's for migrating older AngularJS apps to React apps using the [strangler pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/strangler).
